[package]
name = "plaza_example_lobby_world"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
plaza = { workspace = true }
plaza_server_utils = { workspace = true }
plaza_lobby = { workspace = true }
plaza_session = { workspace = true, features = ["actix_ws", "json", "actix_host"] }
plaza_wire = { workspace = true }

actix-web = "^4"
async-trait = { workspace = true }
parking_lot = "^0.12"
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
plaza_wire = { workspace = true, features = ["build"] }
