// Generated by plaza_wire::build from the paired server's wire sources.
// Do not edit; the server's build script rewrites it when the wire changes.

/// The wire format's version, hashed from the Rust sources that define it.
const int wireProtocol = 225361261;
