// Generated by plaza_wire::build::Wire::dart_types from the server's wire
// definitions. Do not edit; the server's build script rewrites it when the
// wire changes.
//
// Every type encodes with `toWire(named: ...)`: compact arrays for plaza's
// MsgPackCodec, named maps for JSON and MsgPackNamedCodec. `fromWire`
// accepts either shape.
// ignore_for_file: unused_element

/// Rust's `std::time::Duration` on the wire: seconds and nanoseconds.
class WireDuration {
  const WireDuration({required this.secs, required this.nanos});
  final int secs;
  final int nanos;
  Object? toWire({bool named = false}) =>
      named ? <String, Object?>{'secs': secs, 'nanos': nanos} : <Object?>[secs, nanos];
  static WireDuration fromWire(Object? wire) {
    if (wire is Map) return WireDuration(secs: wire['secs'] as int, nanos: wire['nanos'] as int);
    final l = wire as List<Object?>;
    return WireDuration(secs: l[0] as int, nanos: l[1] as int);
  }
}

class Card {
  const Card(this.value);
  final int value;

  Object? toWire({bool named = false}) {
    final v = value;
    return v;
  }

  static Card fromWire(Object? wire) => Card(wire as int);
}

class LinkQuality {
  const LinkQuality({required this.measuredRttMs, required this.assignedExtraMs, required this.oneWayMs});
  final int measuredRttMs;
  final int assignedExtraMs;
  final int oneWayMs;

  Object? toWire({bool named = false}) {
    final measuredRttMs0 = measuredRttMs;
    final assignedExtraMs0 = assignedExtraMs;
    final oneWayMs0 = oneWayMs;
    return named
        ? <String, Object?>{'measured_rtt_ms': measuredRttMs0, 'assigned_extra_ms': assignedExtraMs0, 'one_way_ms': oneWayMs0}
        : <Object?>[measuredRttMs0, assignedExtraMs0, oneWayMs0];
  }

  static LinkQuality fromWire(Object? wire) {
    if (wire is Map) {
      return LinkQuality(measuredRttMs: wire['measured_rtt_ms'] as int, assignedExtraMs: wire['assigned_extra_ms'] as int, oneWayMs: wire['one_way_ms'] as int);
    }
    final l = wire as List<Object?>;
    return LinkQuality(measuredRttMs: l[0] as int, assignedExtraMs: l[1] as int, oneWayMs: l[2] as int);
  }
}

sealed class LobbyOp {
  const LobbyOp();
  Object? toWire({bool named = false});

  static LobbyOp fromWire(Object? wire) {
    if (wire is String) {
      switch (wire) {
      case 'ListTables':
        return const LobbyOpListTables();
      case 'QuickMatch':
        return const LobbyOpQuickMatch();
      case 'LeaveQueue':
        return const LobbyOpLeaveQueue();
      case 'QueueLeft':
        return const LobbyOpQueueLeft();
      }
      throw FormatException('unknown LobbyOp variant: $wire');
    }
    final m = wire as Map;
    final name = m.keys.first as String;
    final body = m[name];
    switch (name) {
      case 'Join': {
        if (body is Map) {
          return LobbyOpJoin(roomId: body['room_id'] as String);
        }
        final bl = body as List<Object?>;
        return LobbyOpJoin(roomId: bl[0] as String);
      }
      case 'Spectate': {
        if (body is Map) {
          return LobbyOpSpectate(roomId: body['room_id'] as String);
        }
        final bl = body as List<Object?>;
        return LobbyOpSpectate(roomId: bl[0] as String);
      }
      case 'Welcome': {
        if (body is Map) {
          return LobbyOpWelcome(you: body['you'] as int, link: LinkQuality.fromWire(body['link']), coins: body['coins'] as int);
        }
        final bl = body as List<Object?>;
        return LobbyOpWelcome(you: bl[0] as int, link: LinkQuality.fromWire(bl[1]), coins: bl[2] as int);
      }
      case 'Catalogue': {
        if (body is Map) {
          return LobbyOpCatalogue(tables: [for (final e in (body['tables'] as List<Object?>)) TableCard.fromWire(e)], link: LinkQuality.fromWire(body['link']));
        }
        final bl = body as List<Object?>;
        return LobbyOpCatalogue(tables: [for (final e in (bl[0] as List<Object?>)) TableCard.fromWire(e)], link: LinkQuality.fromWire(bl[1]));
      }
      case 'Queued': {
        if (body is Map) {
          return LobbyOpQueued(position: body['position'] as int, needed: body['needed'] as int, patienceMs: body['patience_ms'] as int);
        }
        final bl = body as List<Object?>;
        return LobbyOpQueued(position: bl[0] as int, needed: bl[1] as int, patienceMs: bl[2] as int);
      }
      case 'Placed': {
        if (body is Map) {
          return LobbyOpPlaced(roomId: body['room_id'] as String, name: body['name'] as String, endpoint: body['endpoint'] as String, spectator: body['spectator'] as bool, coins: body['coins'] as int);
        }
        final bl = body as List<Object?>;
        return LobbyOpPlaced(roomId: bl[0] as String, name: bl[1] as String, endpoint: bl[2] as String, spectator: bl[3] as bool, coins: bl[4] as int);
      }
      case 'Refused': {
        if (body is Map) {
          return LobbyOpRefused(roomId: body['room_id'] as String, reason: body['reason'] as String, measuredOneWayMs: body['measured_one_way_ms'] as int, allowedOneWayMs: body['allowed_one_way_ms'] == null ? null : body['allowed_one_way_ms'] as int);
        }
        final bl = body as List<Object?>;
        return LobbyOpRefused(roomId: bl[0] as String, reason: bl[1] as String, measuredOneWayMs: bl[2] as int, allowedOneWayMs: bl[3] == null ? null : bl[3] as int);
      }
    }
    throw FormatException('unknown LobbyOp variant: $name');
  }
}

class LobbyOpListTables extends LobbyOp {
  const LobbyOpListTables();
  @override
  Object? toWire({bool named = false}) => 'ListTables';
}

class LobbyOpQuickMatch extends LobbyOp {
  const LobbyOpQuickMatch();
  @override
  Object? toWire({bool named = false}) => 'QuickMatch';
}

class LobbyOpLeaveQueue extends LobbyOp {
  const LobbyOpLeaveQueue();
  @override
  Object? toWire({bool named = false}) => 'LeaveQueue';
}

class LobbyOpJoin extends LobbyOp {
  const LobbyOpJoin({required this.roomId});
  final String roomId;
  @override
  Object? toWire({bool named = false}) {
    final roomId0 = roomId;
    return <String, Object?>{
      'Join': named
          ? <String, Object?>{'room_id': roomId0}
          : <Object?>[roomId0],
    };
  }
}

class LobbyOpSpectate extends LobbyOp {
  const LobbyOpSpectate({required this.roomId});
  final String roomId;
  @override
  Object? toWire({bool named = false}) {
    final roomId0 = roomId;
    return <String, Object?>{
      'Spectate': named
          ? <String, Object?>{'room_id': roomId0}
          : <Object?>[roomId0],
    };
  }
}

class LobbyOpWelcome extends LobbyOp {
  const LobbyOpWelcome({required this.you, required this.link, required this.coins});
  final int you;
  final LinkQuality link;
  final int coins;
  @override
  Object? toWire({bool named = false}) {
    final you0 = you;
    final link0 = link;
    final coins0 = coins;
    return <String, Object?>{
      'Welcome': named
          ? <String, Object?>{'you': you0, 'link': link0.toWire(named: named), 'coins': coins0}
          : <Object?>[you0, link0.toWire(named: named), coins0],
    };
  }
}

class LobbyOpCatalogue extends LobbyOp {
  const LobbyOpCatalogue({required this.tables, required this.link});
  final List<TableCard> tables;
  final LinkQuality link;
  @override
  Object? toWire({bool named = false}) {
    final tables0 = tables;
    final link0 = link;
    return <String, Object?>{
      'Catalogue': named
          ? <String, Object?>{'tables': [for (final e in tables0) e.toWire(named: named)], 'link': link0.toWire(named: named)}
          : <Object?>[[for (final e in tables0) e.toWire(named: named)], link0.toWire(named: named)],
    };
  }
}

class LobbyOpQueued extends LobbyOp {
  const LobbyOpQueued({required this.position, required this.needed, required this.patienceMs});
  final int position;
  final int needed;
  final int patienceMs;
  @override
  Object? toWire({bool named = false}) {
    final position0 = position;
    final needed0 = needed;
    final patienceMs0 = patienceMs;
    return <String, Object?>{
      'Queued': named
          ? <String, Object?>{'position': position0, 'needed': needed0, 'patience_ms': patienceMs0}
          : <Object?>[position0, needed0, patienceMs0],
    };
  }
}

class LobbyOpQueueLeft extends LobbyOp {
  const LobbyOpQueueLeft();
  @override
  Object? toWire({bool named = false}) => 'QueueLeft';
}

class LobbyOpPlaced extends LobbyOp {
  const LobbyOpPlaced({required this.roomId, required this.name, required this.endpoint, required this.spectator, required this.coins});
  final String roomId;
  final String name;
  final String endpoint;
  final bool spectator;
  final int coins;
  @override
  Object? toWire({bool named = false}) {
    final roomId0 = roomId;
    final name0 = name;
    final endpoint0 = endpoint;
    final spectator0 = spectator;
    final coins0 = coins;
    return <String, Object?>{
      'Placed': named
          ? <String, Object?>{'room_id': roomId0, 'name': name0, 'endpoint': endpoint0, 'spectator': spectator0, 'coins': coins0}
          : <Object?>[roomId0, name0, endpoint0, spectator0, coins0],
    };
  }
}

class LobbyOpRefused extends LobbyOp {
  const LobbyOpRefused({required this.roomId, required this.reason, required this.measuredOneWayMs, required this.allowedOneWayMs});
  final String roomId;
  final String reason;
  final int measuredOneWayMs;
  final int? allowedOneWayMs;
  @override
  Object? toWire({bool named = false}) {
    final roomId0 = roomId;
    final reason0 = reason;
    final measuredOneWayMs0 = measuredOneWayMs;
    final allowedOneWayMs0 = allowedOneWayMs;
    return <String, Object?>{
      'Refused': named
          ? <String, Object?>{'room_id': roomId0, 'reason': reason0, 'measured_one_way_ms': measuredOneWayMs0, 'allowed_one_way_ms': allowedOneWayMs0 == null ? null : allowedOneWayMs0}
          : <Object?>[roomId0, reason0, measuredOneWayMs0, allowedOneWayMs0 == null ? null : allowedOneWayMs0],
    };
  }
}

class PhaseChangedNoticePayloadTablePhase {
  const PhaseChangedNoticePayloadTablePhase({required this.newPhase, required this.previousPhase, required this.durationHint, required this.reason});
  final TablePhase newPhase;
  final TablePhase? previousPhase;
  final WireDuration? durationHint;
  final String? reason;

  Object? toWire({bool named = false}) {
    final newPhase0 = newPhase;
    final previousPhase0 = previousPhase;
    final durationHint0 = durationHint;
    final reason0 = reason;
    return named
        ? <String, Object?>{'new_phase': newPhase0.toWire(named: named), 'previous_phase': previousPhase0 == null ? null : previousPhase0.toWire(named: named), 'duration_hint': durationHint0 == null ? null : durationHint0.toWire(named: named), 'reason': reason0 == null ? null : reason0}
        : <Object?>[newPhase0.toWire(named: named), previousPhase0 == null ? null : previousPhase0.toWire(named: named), durationHint0 == null ? null : durationHint0.toWire(named: named), reason0 == null ? null : reason0];
  }

  static PhaseChangedNoticePayloadTablePhase fromWire(Object? wire) {
    if (wire is Map) {
      return PhaseChangedNoticePayloadTablePhase(newPhase: TablePhase.fromWire(wire['new_phase']), previousPhase: wire['previous_phase'] == null ? null : TablePhase.fromWire(wire['previous_phase']), durationHint: wire['duration_hint'] == null ? null : WireDuration.fromWire(wire['duration_hint']), reason: wire['reason'] == null ? null : wire['reason'] as String);
    }
    final l = wire as List<Object?>;
    return PhaseChangedNoticePayloadTablePhase(newPhase: TablePhase.fromWire(l[0]), previousPhase: l[1] == null ? null : TablePhase.fromWire(l[1]), durationHint: l[2] == null ? null : WireDuration.fromWire(l[2]), reason: l[3] == null ? null : l[3] as String);
  }
}

class PlayerView {
  const PlayerView({required this.table, required this.phase, required this.round, required this.totalRounds, required this.whoseTurn, required this.yourSeat, required this.stake, required this.coins, required this.myHand, required this.opponents, required this.played, required this.scores, required this.seatsTaken, required this.seatsTotal, required this.spectators, required this.bots});
  final String table;
  final TablePhase phase;
  final int round;
  final int? totalRounds;
  final int? whoseTurn;
  final Seat? yourSeat;
  final int stake;
  final int coins;
  final List<Card> myHand;
  final List<(int, int)> opponents;
  final List<(int, Card)> played;
  final List<(int, int)> scores;
  final int seatsTaken;
  final int seatsTotal;
  final int spectators;
  final int bots;

  Object? toWire({bool named = false}) {
    final table0 = table;
    final phase0 = phase;
    final round0 = round;
    final totalRounds0 = totalRounds;
    final whoseTurn0 = whoseTurn;
    final yourSeat0 = yourSeat;
    final stake0 = stake;
    final coins0 = coins;
    final myHand0 = myHand;
    final opponents0 = opponents;
    final played0 = played;
    final scores0 = scores;
    final seatsTaken0 = seatsTaken;
    final seatsTotal0 = seatsTotal;
    final spectators0 = spectators;
    final bots0 = bots;
    return named
        ? <String, Object?>{'table': table0, 'phase': phase0.toWire(named: named), 'round': round0, 'total_rounds': totalRounds0 == null ? null : totalRounds0, 'whose_turn': whoseTurn0 == null ? null : whoseTurn0, 'your_seat': yourSeat0 == null ? null : yourSeat0.toWire(named: named), 'stake': stake0, 'coins': coins0, 'my_hand': [for (final e in myHand0) e.toWire(named: named)], 'opponents': [for (final e in opponents0) <Object?>[e.$1, e.$2]], 'played': [for (final e in played0) <Object?>[e.$1, e.$2.toWire(named: named)]], 'scores': [for (final e in scores0) <Object?>[e.$1, e.$2]], 'seats_taken': seatsTaken0, 'seats_total': seatsTotal0, 'spectators': spectators0, 'bots': bots0}
        : <Object?>[table0, phase0.toWire(named: named), round0, totalRounds0 == null ? null : totalRounds0, whoseTurn0 == null ? null : whoseTurn0, yourSeat0 == null ? null : yourSeat0.toWire(named: named), stake0, coins0, [for (final e in myHand0) e.toWire(named: named)], [for (final e in opponents0) <Object?>[e.$1, e.$2]], [for (final e in played0) <Object?>[e.$1, e.$2.toWire(named: named)]], [for (final e in scores0) <Object?>[e.$1, e.$2]], seatsTaken0, seatsTotal0, spectators0, bots0];
  }

  static PlayerView fromWire(Object? wire) {
    if (wire is Map) {
      return PlayerView(table: wire['table'] as String, phase: TablePhase.fromWire(wire['phase']), round: wire['round'] as int, totalRounds: wire['total_rounds'] == null ? null : wire['total_rounds'] as int, whoseTurn: wire['whose_turn'] == null ? null : wire['whose_turn'] as int, yourSeat: wire['your_seat'] == null ? null : Seat.fromWire(wire['your_seat']), stake: wire['stake'] as int, coins: wire['coins'] as int, myHand: [for (final e in (wire['my_hand'] as List<Object?>)) Card.fromWire(e)], opponents: [for (final e in (wire['opponents'] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, t[1] as int); })()], played: [for (final e in (wire['played'] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, Card.fromWire(t[1])); })()], scores: [for (final e in (wire['scores'] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, t[1] as int); })()], seatsTaken: wire['seats_taken'] as int, seatsTotal: wire['seats_total'] as int, spectators: wire['spectators'] as int, bots: wire['bots'] as int);
    }
    final l = wire as List<Object?>;
    return PlayerView(table: l[0] as String, phase: TablePhase.fromWire(l[1]), round: l[2] as int, totalRounds: l[3] == null ? null : l[3] as int, whoseTurn: l[4] == null ? null : l[4] as int, yourSeat: l[5] == null ? null : Seat.fromWire(l[5]), stake: l[6] as int, coins: l[7] as int, myHand: [for (final e in (l[8] as List<Object?>)) Card.fromWire(e)], opponents: [for (final e in (l[9] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, t[1] as int); })()], played: [for (final e in (l[10] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, Card.fromWire(t[1])); })()], scores: [for (final e in (l[11] as List<Object?>)) (() { final t = e as List<Object?>; return (t[0] as int, t[1] as int); })()], seatsTaken: l[12] as int, seatsTotal: l[13] as int, spectators: l[14] as int, bots: l[15] as int);
  }
}

class RoundEndedNoticePayloadRoundSummary {
  const RoundEndedNoticePayloadRoundSummary({required this.roundNumber, required this.reason, required this.summaryData});
  final int roundNumber;
  final String reason;
  final RoundSummary? summaryData;

  Object? toWire({bool named = false}) {
    final roundNumber0 = roundNumber;
    final reason0 = reason;
    final summaryData0 = summaryData;
    return named
        ? <String, Object?>{'round_number': roundNumber0, 'reason': reason0, 'summary_data': summaryData0 == null ? null : summaryData0.toWire(named: named)}
        : <Object?>[roundNumber0, reason0, summaryData0 == null ? null : summaryData0.toWire(named: named)];
  }

  static RoundEndedNoticePayloadRoundSummary fromWire(Object? wire) {
    if (wire is Map) {
      return RoundEndedNoticePayloadRoundSummary(roundNumber: wire['round_number'] as int, reason: wire['reason'] as String, summaryData: wire['summary_data'] == null ? null : RoundSummary.fromWire(wire['summary_data']));
    }
    final l = wire as List<Object?>;
    return RoundEndedNoticePayloadRoundSummary(roundNumber: l[0] as int, reason: l[1] as String, summaryData: l[2] == null ? null : RoundSummary.fromWire(l[2]));
  }
}

class RoundStartedNoticePayload {
  const RoundStartedNoticePayload({required this.roundNumber, required this.totalRounds});
  final int roundNumber;
  final int? totalRounds;

  Object? toWire({bool named = false}) {
    final roundNumber0 = roundNumber;
    final totalRounds0 = totalRounds;
    return named
        ? <String, Object?>{'round_number': roundNumber0, 'total_rounds': totalRounds0 == null ? null : totalRounds0}
        : <Object?>[roundNumber0, totalRounds0 == null ? null : totalRounds0];
  }

  static RoundStartedNoticePayload fromWire(Object? wire) {
    if (wire is Map) {
      return RoundStartedNoticePayload(roundNumber: wire['round_number'] as int, totalRounds: wire['total_rounds'] == null ? null : wire['total_rounds'] as int);
    }
    final l = wire as List<Object?>;
    return RoundStartedNoticePayload(roundNumber: l[0] as int, totalRounds: l[1] == null ? null : l[1] as int);
  }
}

class RoundSummary {
  const RoundSummary({required this.winner, required this.winningCard});
  final int? winner;
  final Card? winningCard;

  Object? toWire({bool named = false}) {
    final winner0 = winner;
    final winningCard0 = winningCard;
    return named
        ? <String, Object?>{'winner': winner0 == null ? null : winner0, 'winning_card': winningCard0 == null ? null : winningCard0.toWire(named: named)}
        : <Object?>[winner0 == null ? null : winner0, winningCard0 == null ? null : winningCard0.toWire(named: named)];
  }

  static RoundSummary fromWire(Object? wire) {
    if (wire is Map) {
      return RoundSummary(winner: wire['winner'] == null ? null : wire['winner'] as int, winningCard: wire['winning_card'] == null ? null : Card.fromWire(wire['winning_card']));
    }
    final l = wire as List<Object?>;
    return RoundSummary(winner: l[0] == null ? null : l[0] as int, winningCard: l[1] == null ? null : Card.fromWire(l[1]));
  }
}

enum Seat {
  player('Player'),
  spectator('Spectator');

  const Seat(this.wireName);
  final String wireName;

  Object? toWire({bool named = false}) => wireName;

  static Seat fromWire(Object? wire) =>
      values.firstWhere((v) => v.wireName == wire as String,
          orElse: () => throw FormatException('unknown Seat variant: $wire'));
}

class TableCard {
  const TableCard({required this.roomId, required this.name, required this.currentPlayers, required this.maxPlayers, required this.budgetMs, required this.playable, required this.fitRank});
  final String roomId;
  final String name;
  final int currentPlayers;
  final int maxPlayers;
  final int? budgetMs;
  final bool playable;
  final int? fitRank;

  Object? toWire({bool named = false}) {
    final roomId0 = roomId;
    final name0 = name;
    final currentPlayers0 = currentPlayers;
    final maxPlayers0 = maxPlayers;
    final budgetMs0 = budgetMs;
    final playable0 = playable;
    final fitRank0 = fitRank;
    return named
        ? <String, Object?>{'room_id': roomId0, 'name': name0, 'current_players': currentPlayers0, 'max_players': maxPlayers0, 'budget_ms': budgetMs0 == null ? null : budgetMs0, 'playable': playable0, 'fit_rank': fitRank0 == null ? null : fitRank0}
        : <Object?>[roomId0, name0, currentPlayers0, maxPlayers0, budgetMs0 == null ? null : budgetMs0, playable0, fitRank0 == null ? null : fitRank0];
  }

  static TableCard fromWire(Object? wire) {
    if (wire is Map) {
      return TableCard(roomId: wire['room_id'] as String, name: wire['name'] as String, currentPlayers: wire['current_players'] as int, maxPlayers: wire['max_players'] as int, budgetMs: wire['budget_ms'] == null ? null : wire['budget_ms'] as int, playable: wire['playable'] as bool, fitRank: wire['fit_rank'] == null ? null : wire['fit_rank'] as int);
    }
    final l = wire as List<Object?>;
    return TableCard(roomId: l[0] as String, name: l[1] as String, currentPlayers: l[2] as int, maxPlayers: l[3] as int, budgetMs: l[4] == null ? null : l[4] as int, playable: l[5] as bool, fitRank: l[6] == null ? null : l[6] as int);
  }
}

sealed class TableOp {
  const TableOp();
  Object? toWire({bool named = false});

  static TableOp fromWire(Object? wire) {
    if (wire is String) {
      switch (wire) {
      }
      throw FormatException('unknown TableOp variant: $wire');
    }
    final m = wire as Map;
    final name = m.keys.first as String;
    final body = m[name];
    switch (name) {
      case 'PlayCard':
        return TableOpPlayCard(Card.fromWire(body));
      case 'Reserve': {
        if (body is Map) {
          return TableOpReserve(player: body['player'] as int);
        }
        final bl = body as List<Object?>;
        return TableOpReserve(player: bl[0] as int);
      }
      case 'Withdraw': {
        if (body is Map) {
          return TableOpWithdraw(player: body['player'] as int);
        }
        final bl = body as List<Object?>;
        return TableOpWithdraw(player: bl[0] as int);
      }
      case 'Snapshot':
        return TableOpSnapshot(PlayerView.fromWire(body));
      case 'CardPlayed': {
        if (body is Map) {
          return TableOpCardPlayed(player: body['player'] as int, card: Card.fromWire(body['card']));
        }
        final bl = body as List<Object?>;
        return TableOpCardPlayed(player: bl[0] as int, card: Card.fromWire(bl[1]));
      }
      case 'PlayedForYou': {
        if (body is Map) {
          return TableOpPlayedForYou(player: body['player'] as int, card: Card.fromWire(body['card']));
        }
        final bl = body as List<Object?>;
        return TableOpPlayedForYou(player: bl[0] as int, card: Card.fromWire(bl[1]));
      }
      case 'TrickWon': {
        if (body is Map) {
          return TableOpTrickWon(player: body['player'] as int, card: Card.fromWire(body['card']));
        }
        final bl = body as List<Object?>;
        return TableOpTrickWon(player: bl[0] as int, card: Card.fromWire(bl[1]));
      }
      case 'Settled': {
        if (body is Map) {
          return TableOpSettled(winner: body['winner'] == null ? null : body['winner'] as int, coins: body['coins'] as int);
        }
        final bl = body as List<Object?>;
        return TableOpSettled(winner: bl[0] == null ? null : bl[0] as int, coins: bl[1] as int);
      }
      case 'Rejected': {
        if (body is Map) {
          return TableOpRejected(reason: body['reason'] as String);
        }
        final bl = body as List<Object?>;
        return TableOpRejected(reason: bl[0] as String);
      }
      case 'Closed': {
        if (body is Map) {
          return TableOpClosed(reason: body['reason'] as String);
        }
        final bl = body as List<Object?>;
        return TableOpClosed(reason: bl[0] as String);
      }
      case 'PhaseChanged':
        return TableOpPhaseChanged(PhaseChangedNoticePayloadTablePhase.fromWire(body));
      case 'TurnChanged':
        return TableOpTurnChanged(TurnChangedNoticePayloadInt.fromWire(body));
      case 'RoundStarted':
        return TableOpRoundStarted(RoundStartedNoticePayload.fromWire(body));
      case 'RoundEnded':
        return TableOpRoundEnded(RoundEndedNoticePayloadRoundSummary.fromWire(body));
    }
    throw FormatException('unknown TableOp variant: $name');
  }
}

class TableOpPlayCard extends TableOp {
  const TableOpPlayCard(this.value);
  final Card value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'PlayCard': v.toWire(named: named)};
  }
}

class TableOpReserve extends TableOp {
  const TableOpReserve({required this.player});
  final int player;
  @override
  Object? toWire({bool named = false}) {
    final player0 = player;
    return <String, Object?>{
      'Reserve': named
          ? <String, Object?>{'player': player0}
          : <Object?>[player0],
    };
  }
}

class TableOpWithdraw extends TableOp {
  const TableOpWithdraw({required this.player});
  final int player;
  @override
  Object? toWire({bool named = false}) {
    final player0 = player;
    return <String, Object?>{
      'Withdraw': named
          ? <String, Object?>{'player': player0}
          : <Object?>[player0],
    };
  }
}

class TableOpSnapshot extends TableOp {
  const TableOpSnapshot(this.value);
  final PlayerView value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'Snapshot': v.toWire(named: named)};
  }
}

class TableOpCardPlayed extends TableOp {
  const TableOpCardPlayed({required this.player, required this.card});
  final int player;
  final Card card;
  @override
  Object? toWire({bool named = false}) {
    final player0 = player;
    final card0 = card;
    return <String, Object?>{
      'CardPlayed': named
          ? <String, Object?>{'player': player0, 'card': card0.toWire(named: named)}
          : <Object?>[player0, card0.toWire(named: named)],
    };
  }
}

class TableOpPlayedForYou extends TableOp {
  const TableOpPlayedForYou({required this.player, required this.card});
  final int player;
  final Card card;
  @override
  Object? toWire({bool named = false}) {
    final player0 = player;
    final card0 = card;
    return <String, Object?>{
      'PlayedForYou': named
          ? <String, Object?>{'player': player0, 'card': card0.toWire(named: named)}
          : <Object?>[player0, card0.toWire(named: named)],
    };
  }
}

class TableOpTrickWon extends TableOp {
  const TableOpTrickWon({required this.player, required this.card});
  final int player;
  final Card card;
  @override
  Object? toWire({bool named = false}) {
    final player0 = player;
    final card0 = card;
    return <String, Object?>{
      'TrickWon': named
          ? <String, Object?>{'player': player0, 'card': card0.toWire(named: named)}
          : <Object?>[player0, card0.toWire(named: named)],
    };
  }
}

class TableOpSettled extends TableOp {
  const TableOpSettled({required this.winner, required this.coins});
  final int? winner;
  final int coins;
  @override
  Object? toWire({bool named = false}) {
    final winner0 = winner;
    final coins0 = coins;
    return <String, Object?>{
      'Settled': named
          ? <String, Object?>{'winner': winner0 == null ? null : winner0, 'coins': coins0}
          : <Object?>[winner0 == null ? null : winner0, coins0],
    };
  }
}

class TableOpRejected extends TableOp {
  const TableOpRejected({required this.reason});
  final String reason;
  @override
  Object? toWire({bool named = false}) {
    final reason0 = reason;
    return <String, Object?>{
      'Rejected': named
          ? <String, Object?>{'reason': reason0}
          : <Object?>[reason0],
    };
  }
}

class TableOpClosed extends TableOp {
  const TableOpClosed({required this.reason});
  final String reason;
  @override
  Object? toWire({bool named = false}) {
    final reason0 = reason;
    return <String, Object?>{
      'Closed': named
          ? <String, Object?>{'reason': reason0}
          : <Object?>[reason0],
    };
  }
}

class TableOpPhaseChanged extends TableOp {
  const TableOpPhaseChanged(this.value);
  final PhaseChangedNoticePayloadTablePhase value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'PhaseChanged': v.toWire(named: named)};
  }
}

class TableOpTurnChanged extends TableOp {
  const TableOpTurnChanged(this.value);
  final TurnChangedNoticePayloadInt value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'TurnChanged': v.toWire(named: named)};
  }
}

class TableOpRoundStarted extends TableOp {
  const TableOpRoundStarted(this.value);
  final RoundStartedNoticePayload value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'RoundStarted': v.toWire(named: named)};
  }
}

class TableOpRoundEnded extends TableOp {
  const TableOpRoundEnded(this.value);
  final RoundEndedNoticePayloadRoundSummary value;
  @override
  Object? toWire({bool named = false}) {
    final v = value;
    return <String, Object?>{'RoundEnded': v.toWire(named: named)};
  }
}

enum TablePhase {
  seating('Seating'),
  dealing('Dealing'),
  playing('Playing'),
  scoring('Scoring'),
  finished('Finished');

  const TablePhase(this.wireName);
  final String wireName;

  Object? toWire({bool named = false}) => wireName;

  static TablePhase fromWire(Object? wire) =>
      values.firstWhere((v) => v.wireName == wire as String,
          orElse: () => throw FormatException('unknown TablePhase variant: $wire'));
}

class TurnChangedNoticePayloadInt {
  const TurnChangedNoticePayloadInt({required this.newTurnActor, required this.previousTurnActor, required this.turnNumber, required this.timeLimitForTurn});
  final int? newTurnActor;
  final int? previousTurnActor;
  final int turnNumber;
  final WireDuration? timeLimitForTurn;

  Object? toWire({bool named = false}) {
    final newTurnActor0 = newTurnActor;
    final previousTurnActor0 = previousTurnActor;
    final turnNumber0 = turnNumber;
    final timeLimitForTurn0 = timeLimitForTurn;
    return named
        ? <String, Object?>{'new_turn_actor': newTurnActor0 == null ? null : newTurnActor0, 'previous_turn_actor': previousTurnActor0 == null ? null : previousTurnActor0, 'turn_number': turnNumber0, 'time_limit_for_turn': timeLimitForTurn0 == null ? null : timeLimitForTurn0.toWire(named: named)}
        : <Object?>[newTurnActor0 == null ? null : newTurnActor0, previousTurnActor0 == null ? null : previousTurnActor0, turnNumber0, timeLimitForTurn0 == null ? null : timeLimitForTurn0.toWire(named: named)];
  }

  static TurnChangedNoticePayloadInt fromWire(Object? wire) {
    if (wire is Map) {
      return TurnChangedNoticePayloadInt(newTurnActor: wire['new_turn_actor'] == null ? null : wire['new_turn_actor'] as int, previousTurnActor: wire['previous_turn_actor'] == null ? null : wire['previous_turn_actor'] as int, turnNumber: wire['turn_number'] as int, timeLimitForTurn: wire['time_limit_for_turn'] == null ? null : WireDuration.fromWire(wire['time_limit_for_turn']));
    }
    final l = wire as List<Object?>;
    return TurnChangedNoticePayloadInt(newTurnActor: l[0] == null ? null : l[0] as int, previousTurnActor: l[1] == null ? null : l[1] as int, turnNumber: l[2] as int, timeLimitForTurn: l[3] == null ? null : WireDuration.fromWire(l[3]));
  }
}
