[package]
name = "rollback_playground"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
plaza_client_utils = { workspace = true, features = ["net-sim"] }

macroquad = "=0.4.15"
egui-macroquad = "=0.17.3"

[lib]
name = "rollback_playground"
path = "src/lib.rs"

[[bin]]
name = "rollback_playground"
path = "src/main.rs"
