// plaza/src/session.rs
use crate::agent::{Agent, AgentId};
use crate::error::{PlazaError, SessionError}; // PlazaError for Result return types
use crate::snapshot::SnapshotData; // We'll define this in snapshot.rs
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
use tokio::sync::broadcast; // For the subscribe methods' return type

/// Opaque identifier for a connection within a session.
/// The specific type can be chosen by the Session implementation (e.g., Uuid, u64, a wrapper).
/// For now, let's use a type alias for flexibility, but Session implementors will decide.
pub type ConnectionId = u64; // Example, could be more complex

/// Specifies the recipient(s) of a message.
#[derive(Debug, Clone)] // ID must be Clone + Debug
pub enum MessageTarget<ID: AgentId> {
  /// Send to all connected agents in the session.
  All,
  /// Send to a specific agent.
  Agent(ID),
  /// Send to a list of specific agents.
  Agents(Vec<ID>),
  /// Send to all agents except one.
  AllExcept(ID),
  /// Send to all agents except those in the list.
  AllExceptThese(Vec<ID>),
  // /// Send to a specific connection ID (more advanced, if Session exposes ConnectionIds)
  // Connection(ConnectionId),
}

/// An operation bundled with its originating agent and intended target(s).
/// This is typically generated by `StateLogic::process_input`.
#[derive(Debug, Clone)] // Op and ID must be Clone + Debug
pub struct TargetedOp<Op, ID: AgentId> {
  /// The agent that was the original source or cause of these operations.
  /// For system-generated ops (e.g., from a TimeStep), this would be `Agent::system()`.
  pub from_agent: Agent<ID>,
  /// The intended recipient(s) of these operations.
  pub target: MessageTarget<ID>,
  /// The batch of operations to be sent.
  pub ops: Vec<Op>,
}

/// Represents the different types of messages that can be exchanged over a `Session`.
/// Generic over the application's `Op` type, `AgentId` type, and `SnapshotPayload` type.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(bound(
    serialize = "Op: Serialize, SnapshotPayload: Serialize", // ID is covered by AgentId trait
    deserialize = "Op: Deserialize<'de>, SnapshotPayload: Deserialize<'de>" // ID is covered
))]pub enum SessionMessage<Op, ID: AgentId, SnapshotPayload> {
  /// A batch of operations from a specific agent.
  /// When received by the server from a client, `from` is the client agent.
  /// When sent by the server to clients, `from` is the agent who originated the ops (could be Agent::System).
  Ops { from: Agent<ID>, ops: Vec<Op> },
  /// A full state snapshot or a significant state update.
  /// Typically sent to a client when they join or to recover from desync.
  StateData {
    from: Agent<ID>,                     // Usually Agent::system() when server sends a snapshot
    data: SnapshotData<SnapshotPayload>, // The actual snapshot payload
  },
  // /// A custom application-defined message. (Potentially for future extension)
  // Custom { kind: String, payload: serde_json::Value },
}

/// Trait defining the contract for a communication session.
///
/// A `Session` is responsible for managing connections with participants (agents)
/// and facilitating the transport of `SessionMessage`s between them and the server logic.
/// Implementations will handle specific protocols (e.g., WebSockets, WebRTC, In-Process).
#[async_trait]
pub trait Session<Op, ID: AgentId, SnapshotPayload>: Send + Sync + 'static {
  // It's Send + Sync + 'static because StateController will hold an Arc<Sess>.

  /// Called when a new agent intends to join the session.
  /// The `Session` implementation should handle the underlying connection establishment
  /// (if applicable) and associate the `agent_info` with that connection.
  ///
  /// # Returns
  /// A unique `ConnectionId` for this agent's connection within the session,
  /// or an error if the agent cannot join (e.g., authentication failed, session full).
  async fn agent_join(&self, agent_info: Agent<ID>) -> Result<ConnectionId, PlazaError<ID>>; // Use PlazaError for consistency

  /// Called when an agent is leaving or has disconnected from the session.
  /// The `Session` implementation should handle cleanup of the associated connection.
  async fn agent_leave(
    &self,
    agent_id: &ID,         // The ID of the agent leaving
    conn_id: ConnectionId, // The connection ID they were associated with
  ) -> Result<(), PlazaError<ID>>;

  /// Sends a `SessionMessage` to the specified target(s).
  /// The `Session` implementation is responsible for serializing the message (if needed)
  /// and routing it to the correct underlying connections based on the `MessageTarget`.
  async fn send_message(
    &self,
    target: MessageTarget<ID>,
    msg: SessionMessage<Op, ID, SnapshotPayload>,
  ) -> Result<(), PlazaError<ID>>;

  /// Subscribes to *incoming* `SessionMessage`s that are intended for server-side processing.
  ///
  /// This is typically used by the `StateController` to receive `SessionMessage::Ops`
  /// from clients. The `Session` implementation filters messages: e.g., it would not
  /// put messages it *sends out* onto this channel.
  ///
  /// Each call should return a new receiver that sees messages from that point onward.
  fn subscribe_to_incoming_messages(&self) -> broadcast::Receiver<SessionMessage<Op, ID, SnapshotPayload>>;
  // Note: broadcast::Receiver<Msg> means Msg must be Clone. SessionMessage is Clone.

  /// Returns a broadcast receiver for notifications when new agents have successfully joined the session.
  /// This is typically used by the `StateController` to know when to send a snapshot.
  fn on_agent_joined(&self) -> broadcast::Receiver<Agent<ID>>; // Agent<ID> must be Clone.

  /// Returns a broadcast receiver for notifications when agents have left the session.
  fn on_agent_left(&self) -> broadcast::Receiver<ID>; // ID must be Clone.
}
