// File: core/src/game_common/flow_control/phases.rs
//! Traits and operation payloads for managing game phases.

use crate::agent::AgentId;
use crate::common::fsm::FsmContext; // Assuming FsmContext is at this path
use serde::{Deserialize, Serialize}; // For op_payloads
use std::fmt::Debug;
use std::time::Duration;

/// Trait for controlling game phases, often implemented using an FSM.
///
/// - `Op`: The application's operation type.
/// - `AppID`: The application's `AgentId` type.
/// - `PhaseId`: Application-defined enum for phase identifiers.
pub trait PhaseController<Op, AppID: AgentId, PhaseId: Clone + Debug + PartialEq> {
  /// Gets the current phase.
  fn current_phase(&self) -> PhaseId;

  /// Attempts to transition to the specified `next_phase_id`.
  /// Implementation would typically consult game rules and current state.
  /// Returns `Ok(())` on successful transition initiation, `Err(ReasonString)` on failure.
  /// This method is expected to enqueue a `PhaseChangedNoticeOp` (via op_payloads)
  /// into the context's operation queue upon successful transition.
  fn request_transition(
    &mut self,
    context: &mut dyn FsmContext<Op, AppID>,
    next_phase_id: PhaseId,
  ) -> Result<(), String>;

  // Optional:
  // fn update_phase_flow(&mut self, context: &mut dyn FsmContext<Op, AppID>);
}

/// Defines common operation payloads related to game phases.
pub mod op_payloads {
  use super::*; // Imports PhaseId, Duration, AgentId (via AppID in PhaseController)

  /// Payload for an Op that signals a phase change in the match flow.
  /// Typically generated by `StateLogic` (driven by a `PhaseController`/FSM) and broadcast to clients.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  #[serde(bound = "PhaseId: Serialize + for<'de2> Deserialize<'de2>")]
  pub struct PhaseChangedNoticePayload<PhaseId: Clone + Debug> {
    pub new_phase: PhaseId,
    pub previous_phase: Option<PhaseId>,
    /// Optional: Hint for how long this new phase might last (e.g., countdown duration).
    pub duration_hint: Option<Duration>,
    pub reason: Option<String>,
  }

  /// Payload for an Op allowing a client (e.g., admin, or via voting) to request a phase transition.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  #[serde(bound = "PhaseId: Serialize + for<'de2> Deserialize<'de2>")]
  pub struct RequestPhaseTransitionPayload<PhaseId: Clone + Debug> {
    pub target_phase: PhaseId,
    // pub requesting_agent_id: Option<AppID>, // If needed for permissions
  }

  /// Payload for an Op to update clients about countdown progress within a phase.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  pub struct CountdownTickNoticePayload {
    pub remaining_seconds: u32, // Or Duration
    /// Optional: An identifier for the phase this countdown belongs to, for client context.
    pub phase_context_id: Option<String>, // Could be PhaseId.to_string() or a custom string
  }
}
