// File: core/src/game_common/flow_control/rounds.rs
//! Traits and operation payloads for managing games structured into multiple rounds.

use crate::agent::AgentId;
use crate::common::fsm::FsmContext; // Assuming FsmContext is at this path
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
// use std::any::Any; // For AppSpecificSummary if it's a dyn Trait or erased type

/// Trait for managing game rounds.
///
/// - `Op`: The application's operation type.
/// - `AppID`: The application's `AgentId` type.
pub trait RoundManager<Op, AppID: AgentId> {
  /// Gets the current round number (e.g., 1-indexed).
  fn current_round(&self) -> u32;

  /// Gets the maximum number of rounds for this match, if defined.
  fn max_rounds(&self) -> Option<u32>;

  /// Attempts to start the next round.
  /// Returns `Ok(())` or `Err(ReasonString)` (e.g., if max rounds reached).
  /// This method is expected to enqueue a `RoundStartedNoticeOp` (via op_payloads)
  /// into the context's operation queue.
  fn start_next_round(&mut self, context: &mut dyn FsmContext<Op, AppID>) -> Result<(), String>;

  /// Ends the current round explicitly.
  /// This method is expected to enqueue a `RoundEndedNoticeOp` (via op_payloads).
  fn end_current_round(
    &mut self,
    context: &mut dyn FsmContext<Op, AppID>,
    reason: String, /*, round_winner_data: Option<AppSpecificWinnerData> */
  );
}

/// Defines common operation payloads related to game rounds.
pub mod op_payloads {
  use super::*; // Imports AgentId (via AppID in RoundManager)
                // use std::any::Any; // If AppSpecificRoundSummaryData is truly generic via dyn Any + serde attributes

  /// Payload for an Op that signals the start of a new round.
  /// Typically generated by `StateLogic` (driven by a `RoundManager`) and broadcast.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  pub struct RoundStartedNoticePayload {
    pub round_number: u32,
    pub total_rounds: Option<u32>, // If a fixed number of rounds is known
  }

  /// Payload for an Op that signals the end of a round.
  /// `AppSpecificRoundSummaryData` would be a type defined by the application,
  /// needing `Clone + Debug + Serialize + Deserialize`.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  #[serde(bound = "AppSpecificRoundSummaryData: Serialize + for<'de2> Deserialize<'de2>")]
    pub struct RoundEndedNoticePayload<AppSpecificRoundSummaryData: Clone + Debug> {
    pub round_number: u32,
    pub reason: String,
    pub summary_data: Option<AppSpecificRoundSummaryData>, // e.g., round winner, scores this round
  }
}
