// File: core/src/game_common/flow_control/turns.rs
//! Traits and operation payloads for managing turns in turn-based games.

use crate::agent::AgentId;
use crate::common::fsm::FsmContext; // Assuming FsmContext is at this path
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
use std::hash::Hash; // For TurnActorId as HashMap key potential
use std::time::Duration;

/// Trait for managing discrete turns for players or teams.
///
/// - `Op`: The application's operation type.
/// - `AppID`: The application's `AgentId` type.
/// - `TurnActorId`: Application-defined type representing whose turn it is (e.g., PlayerId, TeamId).
pub trait TurnManager<Op, AppID: AgentId, TurnActorId> {
  /// Gets the ID of the entity whose turn it currently is.
  fn current_turn_actor(&self) -> Option<TurnActorId>;

  /// Attempts to end the current turn and advance to the next.
  /// Implementation determines turn order (e.g., round-robin, custom logic).
  /// Returns `Ok(Option<NextTurnActorId>)` where `None` might indicate end of round/all turns.
  /// This method is expected to enqueue a `TurnChangedNoticeOp` (via op_payloads)
  /// into the context's operation queue upon successful advancement.
  fn end_current_turn_and_advance(
    &mut self,
    context: &mut dyn FsmContext<Op, AppID>,
  ) -> Result<Option<TurnActorId>, String>; // String is error reason

  // Optional:
  // fn set_turn_actor(&mut self, context: &mut dyn FsmContext<Op, AppID>, actor_id: TurnActorId) -> Result<(), String>;
  // fn turn_order(&self) -> Vec<TurnActorId>;
}

/// Defines common operation payloads related to game turns.
pub mod op_payloads {
  use super::*; // Imports TurnActorId, Duration, AgentId (via AppID in TurnManager)

  /// Payload for an Op sent by a client to indicate they are ending their turn.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  #[serde(bound = "")]
  pub struct EndTurnRequestPayload<AppID: AgentId> {
    // AppID from TurnManager
    pub player_id: AppID, // The player making the request (for validation)
  }

  /// Payload for an Op that signals a change in whose turn it is.
  /// Typically generated by `StateLogic` (driven by a `TurnManager`) and broadcast to clients.
  #[derive(Serialize, Deserialize, Debug, Clone)]
  #[serde(bound = "TurnActorId: Serialize + for<'de2> Deserialize<'de2>")]
  pub struct TurnChangedNoticePayload<TurnActorId: Clone + Debug> {
    pub new_turn_actor: Option<TurnActorId>, // None if, e.g., turns are over for a round
    pub previous_turn_actor: Option<TurnActorId>,
    pub turn_number: u32,                      // Overall turn number in the match/round
    pub time_limit_for_turn: Option<Duration>, // Optional time limit for the new turn
  }
}
