[package]
name = "plaza-example-shared-counter"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
plaza = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }