//! The transport abstraction: how a controller reaches its clients.
//!
//! Implement [`Session`] for a new transport, or use one that ships already:
//! [`InProcessSession`] here for local play and tests, and the WebSocket and
//! TCP transports in the `plaza_session` crate for real networking.

pub mod in_process;

pub use in_process::InProcessSession;

use crate::agent::{Agent, AgentId};
use crate::error::PlazaError;
use async_trait::async_trait;
use fibre::mpsc;

/// Identifies one connection within a session. Assigned by the `Session`.
pub type ConnectionId = u64;

/// Default depth for a session's notification channels.
pub const DEFAULT_SESSION_CAPACITY: usize = 256;

/// Receiving end of one of a [`Session`]'s notification streams.
///
/// Many producers (one per connection) feed a single consumer (the controller),
/// so these are MPSC queues rather than broadcasts: nothing is cloned for
/// fan-out that does not happen, and a slow consumer applies backpressure
/// instead of silently dropping messages.
pub type SessionReceiver<T> = mpsc::BoundedAsyncReceiver<T>;

/// Sending end of one of a [`Session`]'s notification streams.
pub type SessionSender<T> = mpsc::BoundedAsyncSender<T>;

/// An agent arriving or leaving.
///
/// One stream rather than two, because the order between them matters: a client
/// that drops and immediately reconnects must not have its departure applied
/// after its return. Separate channels give no ordering guarantee.
#[derive(Debug, Clone)]
pub enum PresenceEvent<ID: AgentId> {
  Joined(Agent<ID>),
  Left(ID),
}

/// Who should receive a message.
///
/// `PartialEq` compares structurally, so `Agents([1, 2])` and `Agents([2, 1])`
/// are unequal despite naming one set. That only costs a coalescing opportunity
/// in [`LogicOutput::coalesce`], never a wrong delivery.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MessageTarget<ID: AgentId> {
  /// Every connected agent.
  All,
  /// One specific agent.
  Agent(ID),
  /// Several specific agents.
  Agents(Vec<ID>),
  /// Everyone but one agent, typically the one who caused the change.
  AllExcept(ID),
  /// Everyone but these agents.
  AllExceptThese(Vec<ID>),
}

/// An operation bundled with its originating agent and intended target(s).
/// This is typically generated by `StateLogic::process_input`.
#[derive(Debug, Clone)]
pub struct TargetedOp<Op, ID: AgentId> {
  /// The agent that was the original source or cause of these operations.
  /// For system-generated ops (e.g., from a TimeStep), this would be `Agent::system()`.
  pub from_agent: Agent<ID>,
  /// The intended recipient(s) of these operations.
  pub target: MessageTarget<ID>,
  /// The batch of operations to be sent.
  pub ops: Vec<Op>,
}

impl<Op, ID: AgentId> TargetedOp<Op, ID> {
  /// Bundles `ops` from `from_agent` for the given `target`.
  pub fn new(from_agent: Agent<ID>, target: MessageTarget<ID>, ops: Vec<Op>) -> Self {
    Self {
      from_agent,
      target,
      ops,
    }
  }

  /// System-originated ops broadcast to every connected agent.
  pub fn new_system_all(ops: Vec<Op>) -> Self {
    Self::new(Agent::system(), MessageTarget::All, ops)
  }

  /// System-originated ops sent to a single agent.
  pub fn new_system_to(agent_id: ID, ops: Vec<Op>) -> Self {
    Self::new(Agent::system(), MessageTarget::Agent(agent_id), ops)
  }
}

/// A batch of ops with the agent that caused them.
///
/// **Server-side only, and deliberately not `Serialize`.** The wire carries
/// `[kind byte][encoded ops]` and nothing else: `from` is the server's own
/// bookkeeping, attached by the transport on the way in and never sent on the
/// way out. Every shipped client already ignored it, because an application
/// that needs to say who did something puts that in the op, at the width it
/// actually needs, which is a seat index rather than a 64-bit identity.
///
/// It sits here beside [`MessageTarget`], [`PresenceEvent`] and [`TargetedOp`]
/// for the same reason they do: routing and plumbing, not vocabulary a client
/// shares.
#[derive(Debug, Clone)]
pub struct SessionMessage<Op, ID: AgentId> {
  /// Inbound, the client the transport attached. Outbound, whoever caused the
  /// ops, which may be [`Agent::System`].
  pub from: Agent<ID>,
  pub ops: Vec<Op>,
}

impl<Op, ID: AgentId> SessionMessage<Op, ID> {
  pub fn new(from: Agent<ID>, ops: Vec<Op>) -> Self {
    Self { from, ops }
  }

  /// Server-originated ops: a snapshot, a timer's effects, anything no client
  /// asked for.
  pub fn system(ops: Vec<Op>) -> Self {
    Self::new(Agent::system(), ops)
  }
}

/// A transport: manages connections with agents and moves `SessionMessage`s
/// between them and the server logic.
///
/// Implementations cover a specific protocol. WebSockets, TCP, in-process.
/// `Send + Sync + 'static` because the `StateController` holds an `Arc<Sess>`;
/// `Op` is `Send` because it crosses task boundaries on the session's channels.
#[async_trait]
pub trait Session<Op: Send + 'static, ID: AgentId>: Send + Sync + 'static {
  /// Registers an agent joining the session, establishing the underlying
  /// connection if the transport needs one.
  ///
  /// Networked transports usually treat joins as implicit, the client connects
  /// and the transport registers it, and return `NotImplemented` here.
  async fn agent_join(&self, agent_info: Agent<ID>) -> Result<ConnectionId, PlazaError<ID>>;

  /// Cleans up after an agent leaves or disconnects.
  async fn agent_leave(&self, agent_id: &ID, conn_id: ConnectionId) -> Result<(), PlazaError<ID>>;

  /// Delivers a message to everyone `target` names, serializing it if the
  /// transport requires that.
  async fn send_message(
    &self,
    target: MessageTarget<ID>,
    msg: SessionMessage<Op, ID>,
  ) -> Result<(), PlazaError<ID>>;

  /// Takes the stream of *inbound* messages headed for server-side processing.
  ///
  /// The `StateController` consumes this to receive clients' ops.
  /// Implementations must not put their own outbound messages here.
  ///
  /// # One consumer
  ///
  /// These three streams deliver each item to exactly one receiver, so a session
  /// feeds exactly one controller, which is already the architecture, since one
  /// controller owns the state. Calling this twice splits the stream between the
  /// two receivers rather than duplicating it; for a second observer (metrics, a
  /// replay log), tee the messages inside your `StateLogic` instead.
  fn subscribe_to_incoming_messages(&self) -> SessionReceiver<SessionMessage<Op, ID>>;

  /// Takes the stream of agents arriving and leaving, in the order they happened.
  ///
  /// A join is what prompts the controller to send a snapshot. See
  /// [`subscribe_to_incoming_messages`](Self::subscribe_to_incoming_messages)
  /// for the one-consumer rule.
  fn on_presence_change(&self) -> SessionReceiver<PresenceEvent<ID>>;
}
