[package]
name = "plaza_example_fog_skirmish"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
plaza = { workspace = true }
plaza_wire = { workspace = true }
plaza_session = { workspace = true, features = ["actix_ws", "json", "actix_host"] }

actix-web = "^4"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[build-dependencies]
plaza_wire = { workspace = true, features = ["build"] }
