[package]
name = "plaza_example_whack_a_mole"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
plaza = { path = "../../core" }

async-trait = "0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4", "serde"] }
